### ISSUE TITLE
How do I download the entire repository, & what are "the appropriate files"?

### ISSUE THREAD

**Issue by JanseenInc** [sealldeveloper/incredibox-modding-docs#2]
I am currently on [this step](https://github.com/sealldeveloper/incredibox-modding-docs/tree/main/Tools/Compiler#windows) and I barely use github so I am confused on how to download the repository, and no buttons that I have tried ended up downloading it. 

I was also looking ahead on the steps, and on step #5, it states to "Put in the appropriate files for your format." What are the appropriate files it's talking about?

Thank you for making Incredimoding so much easier. Hope you see this.

**Comment by sealldeveloper** [comment]
The appropriate files are talking about what format to have the files in, for example if you put a compiled version of a Windows zip, it will use that. Essentially just whatever version you put in.
